### ISSUE TITLE
پایه اولیه برای شروع

### ISSUE THREAD

**Issue by ashkansdg** [QuranPalace/QuranPalacePhase2#2]

**Comment by meahmadi** [comment]
لطفا این صفحه را ببینید و آقا محمدرضا زحمت بکشد و این را با pencil 
ux را کامل کند
[QuranProject First Design](https://github.com/QuranPalace/QuranPalacePhase2/blob/master/QuranProject/Design/960230.md)

**Comment by meahmadi** [comment]
یک نمونه فایل کامل طراحی شده قرآن نیز براتون قرار میدهم تا هرجا تو تبیینش مشکل داشتید بنا رو بر اون فایل بگذارید و  فایل جدید رو نیز بر همین اساس کامل کنید
