### ISSUE TITLE
لیست نیازهای الان برای نرم‌افزار قرآن علاوه بر پیش طرح قبلی

### ISSUE THREAD

**Issue by meahmadi** [QuranPalace/QuranPalacePhase2#5]
ارسال لیست نیازهای جدید به آقا محمدرضا

**Comment by bahrami703** [comment]
من منتظر هستم

**Comment by meahmadi** [comment]
قربانت :) 
در جلسه https://github.com/QuranPalace/QuranPalacePhase2/blob/master/Sessions/QuranProject/960306-Design.md به صورت حضوری ارائه شد
